apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  selector:
    matchLabels:
      app: consumer
  replicas: 1
  template:
    metadata:
      labels:
        app: consumer
    spec:
      initContainers:
        - name: sleep
          image: busybox:1.28
          command: ["sleep", "30"]
      containers:
      - name: consumer
        image: 437319827628.dkr.ecr.us-east-1.amazonaws.com/projeto
        imagePullPolicy: Always
        command:
        - python
        args:
        - consumer.py

# executa o módulo consumer que fica aguardando a fila do RabbitMQ
