on:
  workflow_dispatch:
    inputs:
      project:
        description: "Project Name"
        required: true
        default: "ada-terraform"
      grupoRevisores:
        description: "Nome do grupo de revisores"
        required: true
        type: choice
        default: "Contributors"
        options:
          - DevOps
          - Contributors
          - CreditoTeam

name: "Create AWS EKS Cluster"

jobs:
  create-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        name: Setup Terraform

      - name: "Terraform Init"
        run: terraform init
        working-directory: ./terraform

      - name: "Terraform Apply"
        run: terraform apply -auto-approve
        if: github.event_name == 'workflow_dispatch'
        working-directory: ./terraform
        env:
          AZDO_ORG_SERVICE_URL: ${{ vars.AZDO_ORG_SERVICE_URL }}
          AZDO_PERSONAL_ACCESS_TOKEN: ${{ secrets.AZDO_PERSONAL_ACCESS_TOKEN }}
          TF_VAR_reviewers_group_name: ${{ inputs.grupoRevisores }}