on:
  push:

name: "Deploy no AWS EKS Cluster"

jobs:
  deploy-aws-cluster:
    runs-on: ubuntu-latest
    environment: "ADA"
    steps:
      - name: Checkout deploy
        uses: actions/checkout@v4

      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v3.0
        with:
          # Acceptable values: generic or arc
          cluster-type: generic
          # Acceptable values: kubeconfig or service-account or service-principal
          method: kubeconfig
          # Contents of kubeconfig file
          kubeconfig: # optional
          # If your kubeconfig has multiple contexts, use this field to use a specific context, otherwise the default one would be chosen
          context: # optional
          # Cluster Url
          k8s-url: # optional
          # Service account secret (run kubectl get serviceaccounts <service-account-name> -o yaml and copy the service-account-secret-name)
          k8s-secret: # optional
          # Token extracted from the secret of service account (should be base 64 decoded)
          token: # optional
          # Azure resource group name
          resource-group: # optional
          # Azure connected cluster name
          cluster-name: # optional

      - name: Kubectl Apply
        # You may pin to the exact commit or the version.
        # uses: okteto/apply@328f43d812068515fb2018820883ab0df07532ca
        uses: okteto/apply@latest
        with:
          # Path to the Kubernetes manifest. Can be a file or a directory
          manifest: ../kubernetes/ 
          # optional, default is k8s.yml
          # If present, the namespace scope for this action. If not specified, it will use the current context
          namespace: # optional
                            
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}

      - name: "Terraform Apply"
        run: terraform apply -auto-approve
        working-directory: ./terraform
        env:
          AZDO_ORG_SERVICE_URL: ${{ vars.AZDO_ORG_SERVICE_URL }}
          AZDO_PERSONAL_ACCESS_TOKEN: ${{ secrets.AZDO_PERSONAL_ACCESS_TOKEN }}
          TF_VAR_reviewers_group_name: ${{ inputs.grupoRevisores }}
          TF_VAR_ami_id: ${{ vars.ami_id }}
          TF_VAR_aws_region: ${{ vars.aws_region }}
          TF_VAR_aws_access_key: ${{ secrets.aws_access_key }}
          TF_VAR_aws_secret_key: ${{ secrets.aws_secret_key }}
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}

      
